### PR TITLE
Fix template evaluation when header is missing

### PR DESCRIPTION
**Pull request by phiz71**
**Issue**

https://github.com/gravitee-io/issues/issues/7283

**Description**

when no header is found, EL should considered headers list as null instead of an empty list

---

📚&nbsp;&nbsp;View the storybook of this branch [here](https://612657caa8e859003a8a6430-waaurawedu.chromatic.com)

🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://apimnightlywebui24386.blob.core.windows.net/7283-el-template-evaluation-on-missing-headers/index.html)
_Notes_: The deployed app is linked to the management API of the Element Zero team's environment.

### CODE REVIEW

**Review by ytvnr — COMMENTED** [review]
can you add a unit test to check the behaviour is the same for different implementation of HttpHeaders ?

**Review by brasseld — CHANGES_REQUESTED** [review]
I find this one a bit dangerous, as you don't know what would be the impact of returning a null now.
Good chances that you could have to deal with NullPointerException in the future...

**Comment by phiz71** [comment]
> I find this one a bit dangerous, as you don't know what would be the impact of returning a null now. Good chances that you could have to deal with NullPointerException in the future...

I agree it was a bit too much. I moved the fix closer to the bug.

**Review by ytvnr — APPROVED** [review]

**Comment by ytvnr** [comment]
⚠️ We also should update the policies and libraries (gateway-api for example) that use an old version of gravitee-expression-language

**Review by gcusnieux — APPROVED** [review]

**Pull request merged**
