### PR TITLE
fix(portal-next): fix app name

### PR DESCRIPTION
**Pull request by illichso**
## Issue

https://gravitee.atlassian.net/browse/APIM-5463

## Description

Remove "x" from app name

## Additional context

Also the fix for this error in console:

Screenshot 2024-08-13 at 11 53 29

https://github.com/user-attachments/assets/dc6af943-6b67-4f1c-be53-b4859f02e7cc

### CODE REVIEW

**Review by jourdiw — APPROVED** [review]

**Review by jourdiw — CHANGES_REQUESTED** [review]
In the demo shown in the PR description, the title no longer has an ellipses:

Screenshot 2024-08-13 at 12 04 18

And it looks like the tooltip does not show the full name (ends with an ellipses). Is it the tooltip that is adding the constraint or is it the data that you are passing to it?

Screenshot 2024-08-13 at 12 05 31

**Comment by illichso** [comment]
This the full name:
Screenshot 2024-08-13 at 12 07 46

So tooltip works as expected

**Comment by jourdiw** [comment]
> This the full name: Screenshot 2024-08-13 at 12 07 46
> 
> So tooltip works as expected

I guess we need to also address in another PR when application title names are long in this view 🙈

**Review by jourdiw — APPROVED** [review]

**Comment by jourdiw** [comment]
> In the demo shown in the PR description, the title no longer has an ellipses:
> 
> Screenshot 2024-08-13 at 12 04 18
> 
> And it looks like the tooltip does not show the full name (ends with an ellipses). Is it the tooltip that is adding the constraint or is it the data that you are passing to it?
> 
> Screenshot 2024-08-13 at 12 05 31

As discussed, will let super long one-word applications be cut off for now...

**Pull request merged**
