### PR TITLE
test(ui): notifications cypress ui tests

### PR DESCRIPTION
**Pull request by RubenMMSantos**
## Issue

https://gravitee.atlassian.net/browse/APIM-XXX

## Description

UI tests for the notifications page that was migrated to Angular (only for V2 apis)

## Additional context

---

📚&nbsp;&nbsp;View the storybook of this branch [here](https://612657caa8e859003a8a6430-htwyfthbyk.chromatic.com)

### CODE REVIEW

**Review by kkibbey1996 — COMMENTED** [review]
Looks all groovy to me! Good job! 👍

It would be good to look into `cy.get('[type="submit"]').contains('Create').click();` and try giving this kind of button a test id (possibly in schema) but I have used this method in other sense so makes sense to refactor with other tests later.

**Review by ctschacher — COMMENTED** [review]
Haven't fully checked on this PR yet but noticed that some of the new tests are failing. Is this under investigation? 
(There are also some api-list test flaky again I might be able to check on that later today.)

**Comment by RubenMMSantos** [comment]
> Looks all groovy to me! Good job! 👍
> 
> It would be good to look into `cy.get('[type="submit"]').contains('Create').click();` and try giving this kind of button a test id (possibly in schema) but I have used this method in other sense so makes sense to refactor with other tests later.

will have a look and try to improve this part

**Comment by RubenMMSantos** [comment]
> Haven't fully checked on this PR yet but noticed that some of the new tests are failing. Is this under investigation? (There are also some api-list test flaky again I might be able to check on that later today.)

Yes, i am currently trying to solve some conflicts with the merges and once that is done i will look into the failing tests

**Pull request merged**
