### PR TITLE
Test/add wsdl import tests

### PR DESCRIPTION
**Pull request by ctschacher**
**Description**
- added tests for WSDL import (via file and URL)
- added more tests for swagger import

**Additional information**
- Currently the test file contains a whole WSDL file as a string, this is temporary and will be corrected once we've changed to Jest (Cypress caused some problems with the import of that kind of file but with Jest it would be much easier)
- No E2E tests for WSDL import were implemented yet, wait for decision about a mock server with would have an impact on how to write these files

gravitee-io/issues#7295

🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://apimnightlywebui24386.blob.core.windows.net/test-add-wsdl-import-tests/index.html)
_Notes_: The deployed app is linked to the management API of APIM master. (Same login and password as APIM master)

### CODE REVIEW

**Comment by gcusnieux** [comment]
Hi @ctschacher well done !
If you agree, I propose to merge the [jest setup](https://github.com/gravitee-io/gravitee-api-management/pull/1640) before this one and to work together to migrate the test to jest in this branch

**Comment by ctschacher** [comment]
@gcusnieux Thanks! And yes, sounds good to me, let's do so.

**Comment by gcusnieux** [comment]
Replaced by https://github.com/gravitee-io/gravitee-api-management/pull/1688 
And I will push gateway test to dedicated issue

**Comment by gcusnieux** [comment]
@ctschacher The dedicated issue for external api call: https://github.com/gravitee-io/issues/issues/7602

**Pull request closed without merging**
