### PR TITLE
feat: enrich additional info from var env for cloud

### PR DESCRIPTION
**Pull request by gcusnieux**
## Issue

https://gravitee.atlassian.net/browse/CJ-1191

## Description

A small description of what you did in that PR.

### CODE REVIEW

**Review by jgiovaresco — COMMENTED** [review]
From what I understand you will also need to update the Helm chart to support the new property 🤔 Did you check this part?

**Comment by gcusnieux** [comment]
> From what I understand you will also need to update the Helm chart to support the new property 🤔 Did you check this part?

yes, that's true, but it's the platform team that has to do it https://gravitee.atlassian.net/browse/TT-4674

**Comment by jhaeyaert** [comment]
> > From what I understand you will also need to update the Helm chart to support the new property 🤔 Did you check this part?
> 
> yes, that's true, but it's the platform team that has to do it https://gravitee.atlassian.net/browse/TT-4674

I think it will be managed through env variables as there is no real external usage see:

> As we don’t have external usage, we will use environment variable, something like this:
> 
> gravitee_installation_additionalInformation_0_name: cp-id
> gravitee_installation_additionalInformation_0_value: efdab34c
> gravitee_installation_additionalInformation_1_name: provider
> gravitee_installation_additionalInformation_1_value: az

**Comment by gcusnieux** [comment]
Yes it's true @jhaeyaert someone can approve @jgiovaresco 🙏 ?

**Review by jhaeyaert — APPROVED** [review]
LGTM but I think you'll need an approval from an APIM guy (and you have Sonar issue that could block the merge)

**Review by jgiovaresco — APPROVED** [review]

**Comment by gcusnieux** [comment]
> LGTM but I think you'll need an approval from an APIM guy (and you have Sonar issue that could block the merge)

Ok thx, I added a test on multi-tenant part 😅

**Comment by gcusnieux** [comment]
What about integration tests ? It's not stable ?

**Pull request merged**
