### PR TITLE
fix(gateway): keep multi values headers 

### PR DESCRIPTION
**Pull request by gcusnieux**
gravitee-io/issues#7325

---

📚&nbsp;&nbsp;View the storybook of this branch [here](https://612657caa8e859003a8a6430-tcaqwhofne.chromatic.com)

🚀 CI was able to deploy the build of this PR, so you can now try it directly [here](https://apimnightlywebui24386.blob.core.windows.net/7325-gateway-headers/index.html)
_Notes_: The deployed app is linked to the management API of the Element Zero team's environment.

### CODE REVIEW

**Review by brasseld — CHANGES_REQUESTED** [review]
I'm a bit concerned by this fix.
It was working well before 3.15.x so I'm wondering why we should introduce such fix now in 3.15.x ?

For me, the gateway should not change the response headers that way.

**Comment by gcusnieux** [comment]
Ok @brasseld forgot my pevious comment, we found the good solution with 🦸 @jhaeyaert, I will update the PR soon

**Review by jhaeyaert — APPROVED** [review]

**Review by gaetanmaisse — APPROVED** [review]

**Comment by gaetanmaisse** [comment]
@brasseld good for you?

**Comment by brasseld** [comment]
Much more better! What I was expecting.

**Pull request merged**
