### PR TITLE
Console - Fix subscription endDate removal & log settings link

### PR DESCRIPTION
**Pull request by ThibaudAV**
## Issue
https://gravitee.atlassian.net/browse/APIM-2606
https://gravitee.atlassian.net/browse/APIM-2739

## Description

Fix souscription endDate removal & log settings link

Improve Ui to have right height of input field
Screenshot 2023-09-29 at 15 56 52

Before : 
image

## Additional context

🏗️ Your changes can be tested here and will be available soon:
      Console: [https://pr.team-apim.gravitee.dev/5416/console](https://pr.team-apim.gravitee.dev/5416/console)
      Portal: [https://pr.team-apim.gravitee.dev/5416/portal](https://pr.team-apim.gravitee.dev/5416/portal)
      Management-api: [https://pr.team-apim.gravitee.dev/5416/api/management](https://pr.team-apim.gravitee.dev/5416/api/management)
      Gateway v4: [https://pr.team-apim.gravitee.dev/5416](https://pr.team-apim.gravitee.dev/5416)
      Gateway v3: [https://pr.gateway-v3.team-apim.gravitee.dev/5416](https://pr.gateway-v3.team-apim.gravitee.dev/5416)

---

📚&nbsp;&nbsp;View the storybook of this branch [here](https://612657caa8e859003a8a6430-iifkwakryg.chromatic.com)

### CODE REVIEW

**Comment by gaetanmaisse** [comment]
I think we should be able to select the time also, and not only the date

**Comment by ThibaudAV** [comment]
yes I saw it, but I don't know why it was deleted or maybe juste forgotten

**Comment by jgiovaresco** [comment]
The link is ✅ 
However, as @gaetanmaisse mentioned, we can't select the time when changing the end date.

**Comment by gaetanmaisse** [comment]
After a discussion we'll merge this PR without the time picker and create a dedicated issue for this

**Review by gaetanmaisse — APPROVED** [review]

**Pull request merged**
