### PR TITLE
Console - application general migration - fifth part

### PR DESCRIPTION
**Pull request by jansobczynski**
## Issue

https://gravitee.atlassian.net/browse/APIM-XXX

## Description

Migrating application general tab - creating User and group access tab

## Additional context

🏗️ Your changes can be tested here and will be available soon:
      Console: [https://pr.team-apim.gravitee.dev/6014/console](https://pr.team-apim.gravitee.dev/6014/console)
      Portal: [https://pr.team-apim.gravitee.dev/6014/portal](https://pr.team-apim.gravitee.dev/6014/portal)
      Management-api: [https://pr.team-apim.gravitee.dev/6014/api/management](https://pr.team-apim.gravitee.dev/6014/api/management)
      Gateway v4: [https://pr.team-apim.gravitee.dev/6014](https://pr.team-apim.gravitee.dev/6014)
      Gateway v3: [https://pr.gateway-v3.team-apim.gravitee.dev/6014](https://pr.gateway-v3.team-apim.gravitee.dev/6014)

---

📚&nbsp;&nbsp;View the storybook of this branch [here](https://612657caa8e859003a8a6430-bkklvdario.chromatic.com)

### CODE REVIEW

**Review by jourdiw — APPROVED** [review]
LGTM

**Comment by jourdiw** [comment]
It looks like there is a line + padding present if no tabs are used in the current view: 

Screenshot 2023-11-28 at 17 06 32

**Review by jourdiw — CHANGES_REQUESTED** [review]
Fix formatting to not show padding + line if no tabs

**Comment by jansobczynski** [comment]
> Fix formatting to not show padding + line if no tabs

Fixed
Screenshot 2023-11-29 at 11 25 04 AM

**Review by jourdiw — APPROVED** [review]

**Pull request merged**
