### PR TITLE
feat: render async api spec in v4 documentation

### PR DESCRIPTION
**Pull request by a-cordier**
see https://gravitee.atlassian.net/browse/APIM-3543

---

📚&nbsp;&nbsp;View the storybook of this branch [here](https://612657caa8e859003a8a6430-ulqxyebuit.chromatic.com)

### CODE REVIEW

**Review by ThibaudAV — COMMENTED** [review]
Have you tested that asyncapi api still works in api v2 documentation ?
And that clients with existing documentation in an older async API format continue to work or there are braking changes on asyncapi side. 💭

**Comment by a-cordier** [comment]
@ThibaudAV I tested the v2 component yes, do we have sample files somewhere to perform the test you are mentioning ?

EDIT also tested with all v3 files in [this directory](https://github.com/asyncapi/spec/tree/master/examples) and v2 examples from the [doc site](https://v2.asyncapi.com/docs/tutorials/getting-started/asyncapi-documents) without issues

**Comment by ThibaudAV** [comment]
👌  I don't really have an example. From what I read on asyncApi it should be good. 🤞 
I'm thinking of our client who already have a doc configured and who are going to migrate to this APIM version. The doc could come from a version 3.5 of APIM or even earlier. So I'm wondering whether cal will continue to work for them or we need to add something into release note 🤷‍♂️

**Comment by ThibaudAV** [comment]
🙈 not working with `https://github.com/asyncapi/spec/blob/master/examples/adeo-kafka-request-reply-asyncapi.yml`

**Review by ThibaudAV — APPROVED** [review]

**Pull request merged**
